# Generated by Django 5.0.4 on 2025-02-02 17:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTickets',
            fields=[
                ('id_tipo_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_Ticket', models.AutoField(primary_key=True, serialize=False)),
                ('precioInicial', models.IntegerField(blank=True, null=True)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qr_tickets')),
                ('usada', models.BooleanField(default=False)),
                ('reservado', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(db_column='evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.evento')),
                ('propietario', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('tipo_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.tipotickets')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_Publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('fecha', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('publica', models.BooleanField(default=True)),
                ('ticket', models.ForeignKey(blank=True, db_column='ticket', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id_Precio', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('fechaInicial', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(blank=True, db_column='ticket', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.ticket')),
            ],
        ),
    ]
