# Generated by Django 4.2.11 on 2024-04-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id_Precio', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('fechaInicial', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_Publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('publica', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_Ticket', models.AutoField(primary_key=True, serialize=False)),
                ('precioInicial', models.FloatField()),
                ('precios', models.ManyToManyField(blank=True, to='tickets.precio')),
                ('publicaciones', models.ManyToManyField(blank=True, to='tickets.publicacion')),
            ],
        ),
    ]
