# Generated by Django 5.0.4 on 2024-04-26 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='precios',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='publicaciones',
        ),
        migrations.AddField(
            model_name='precio',
            name='ticket',
            field=models.ForeignKey(blank=True, db_column='ticket', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='ticket',
            field=models.ForeignKey(blank=True, db_column='ticket', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.ticket'),
        ),
    ]
