# Generated by Django 5.0.4 on 2024-05-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='propietario',
            field=models.BooleanField(default=False),
        ),
    ]
