# Generated by Django 5.0.4 on 2024-05-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
