# Generated by Django 5.0.4 on 2024-05-01 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_publicacion_fecha'),
        ('usuarios', '0004_alter_usuario_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente'),
        ),
    ]
