# Generated by Django 5.0.4 on 2024-05-02 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_evento_canttickets'),
        ('tickets', '0008_alter_ticket_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='evento',
            field=models.ForeignKey(db_column='evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.evento'),
        ),
    ]
