# Generated by Django 5.0.4 on 2024-05-04 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTickets',
            fields=[
                ('id_tipo_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tickets.tipotickets'),
        ),
    ]
