# Generated by Django 5.0.4 on 2024-05-04 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_tipotickets_ticket_tipo_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tipo_ticket',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.tipotickets'),
        ),
    ]
