# Generated by Django 5.0.4 on 2024-05-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_tipo_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotickets',
            name='tipo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
