# Generated by Django 5.0.4 on 2024-05-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_ticket_tipo_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='precioInicial',
            field=models.IntegerField(),
        ),
    ]
