# Generated by Django 5.0.4 on 2024-05-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_ticket_evento_alter_ticket_precioinicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tipo_ticket',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='precioInicial',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
