# Generated by Django 5.0.4 on 2024-05-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_remove_ticket_tipo_ticket_alter_ticket_precioinicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='precioInicial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
