# Generated by Django 5.0.4 on 2024-05-04 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_alter_ticket_precioinicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tipo_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.tipotickets'),
        ),
    ]
