# Generated by Django 5.0.4 on 2024-05-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_ticket_tipo_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_tickets'),
        ),
    ]
