# Generated by Django 5.0.4 on 2024-05-25 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_ticket_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
