# Generated by Django 5.0.4 on 2025-12-19 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_evento_revalorizacion'),
        ('tickets', '0025_ticket_usada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='historial_propietarios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='evento',
            field=models.ForeignKey(blank=True, db_column='evento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.evento'),
        ),
    ]
