# Generated by Django 5.0.4 on 2025-12-20 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_ticket_historial_propietarios_alter_ticket_evento'),
        ('usuarios', '0017_usuario_mp_access_token_usuario_mp_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cliente_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_en_reserva', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reserva_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
