# Generated by Django 5.0.4 on 2025-12-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_ticket_cliente_reserva_ticket_reserva_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reserva_timestamp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
