# Generated by Django 5.0.4 on 2025-12-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_ticket_reserva_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='razon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
