# Generated by Django 5.0.4 on 2025-12-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_ticket_razon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='razon',
        ),
        migrations.AddField(
            model_name='precio',
            name='razon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
