apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "backend-cert"
    kubernetes.io/ingress.global-static-ip-name: "backend-static-ip"
    ingress.gcp.kubernetes.io/backend-config: '{"backend-service": "backend-health-check-config"}'
spec:
  rules:
    - host: api.unlucoin.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
  tls:
    - hosts:
        - api.unlucoin.info
