apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "backend-cert" # Nuevo certificado para la API
    kubernetes.io/ingress.global-static-ip-name: "backend-static-ip"
    # Agrega esta anotación para el BackendConfig
    ingress.gcp.kubernetes.io/backend-config: '{"backend-service": "backend-health-check-config"}'
spec:
  rules:
    - host: api.unlucoin.info # <--- ¡Nuevo subdominio para tu API!
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000