apiVersion: apps/v1
kind: Deployment
metadata:
  name: bypass-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bypass-frontend
  template:
    metadata:
      labels:
        app: bypass-frontend
    spec:
      containers:
        - name: bypass-frontend
          image: lucaslatessa/bypass-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: bypass-frontend
  ports:
    - port: 80
      targetPort: 80
