# Generated by Django 5.0.4 on 2025-02-02 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id_Transferencia', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Hora', models.DateTimeField()),
                ('Precio', models.FloatField()),
                ('Comprador', models.ForeignKey(db_column='Comprador', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Comprador', to='usuarios.usuario')),
                ('Ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.ticket')),
                ('Vendedor', models.ForeignKey(db_column='Vendedor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Vendedor', to='usuarios.usuario')),
            ],
        ),
    ]
