# Generated by Django 5.0.4 on 2024-04-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
                ('nickname', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('correo', models.TextField()),
                ('creacion', models.TextField()),
                ('rol', models.TextField()),
            ],
        ),
    ]
