# Generated by Django 5.0.4 on 2024-04-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
