# Generated by Django 5.0.4 on 2024-05-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
