# Generated by Django 5.0.4 on 2024-05-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_administrador_dni_alter_cliente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
