# Generated by Django 5.0.4 on 2024-05-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_administrador_dni_alter_cliente_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='creacion',
            field=models.DateTimeField(),
        ),
    ]
