# Generated by Django 5.0.4 on 2024-05-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
