# Generated by Django 5.0.4 on 2024-05-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_usuario_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
