# Generated by Django 5.0.4 on 2024-05-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_usuario_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
