# Generated by Django 5.0.4 on 2024-06-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Access_Token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Public_Key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
