# Generated by Django 5.0.4 on 2025-12-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_usuario_access_token_usuario_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mp_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mp_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mp_state',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mp_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
