# Generated by Django 5.0.4 on 2024-05-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id_beneficio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('porcentajeDescuento', models.IntegerField(null=True)),
                ('codigoDescuento', models.IntegerField()),
                ('usado', models.BooleanField()),
            ],
        ),
    ]
