# Generated by Django 5.0.4 on 2024-05-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0002_alter_beneficio_porcentajedescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='beneficios'),
        ),
    ]
