# Generated by Django 5.0.4 on 2024-06-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0004_beneficio_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
