# Generated by Django 5.0.4 on 2024-04-20 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEvento',
            fields=[
                ('id_Estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id_Lugar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_Evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.estadoevento')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.lugar')),
            ],
        ),
    ]
