# Generated by Django 5.0.4 on 2024-04-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha',
        ),
    ]
