# Generated by Django 5.0.4 on 2024-04-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_estado_alter_evento_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
