# Generated by Django 5.0.4 on 2024-04-20 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.ForeignKey(blank=True, db_column='estadoEvento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.estadoevento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.ForeignKey(blank=True, db_column='lugar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.lugar'),
        ),
    ]
