# Generated by Django 5.0.4 on 2024-05-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_evento_estado_alter_evento_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(null=True, upload_to='eventos'),
        ),
    ]
