# Generated by Django 5.0.4 on 2024-05-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_evento_hora_alter_evento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cantTickets',
            field=models.IntegerField(default=0),
        ),
    ]
