# Generated by Django 5.0.4 on 2024-05-25 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_evento_descripcion'),
        ('usuarios', '0015_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='productora',
            field=models.ForeignKey(blank=True, db_column='nickname', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.productora'),
        ),
    ]
