# Generated by Django 5.0.4 on 2024-06-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_alter_evento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cantTicketsTotal',
            field=models.IntegerField(default=0),
        ),
    ]
