# Generated by Django 5.0.4 on 2025-12-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_evento_cantticketstotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='revalorizacion',
            field=models.BooleanField(default=True),
        ),
    ]
