# Generated by Django 5.0.4 on 2025-12-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_evento_revalorizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='cantTickets',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='cantTicketsTotal',
        ),
        migrations.AddField(
            model_name='evento',
            name='razon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
