# Generated by Django 5.0.4 on 2024-06-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_alter_evento_entradasdisponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='entradasDisponibles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
