# Generated by Django 5.0.4 on 2024-06-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_alter_evento_entradasdisponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='entradasDisponibles',
            field=models.IntegerField(default=0),
        ),
    ]
