# Generated by Django 5.0.4 on 2025-12-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_remove_evento_canttickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='razon',
        ),
    ]
