# Generated by Django 5.0.4 on 2025-12-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_remove_evento_razon'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ultima_revalorizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
