name: Build y Push Docker Images a Docker Hub

on:
  push: #rama
    branches: [ despliegue ]
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Autenticacion Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

      - name: Instalar gcloud y kubectl
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
          install_components: 'kubectl'

      - name: Obtener credenciales de GKE
        run: |
          gcloud container clusters get-credentials gke-cluster --region=us-east4 --project=psychic-expanse-465922-f0

      - name: Aplicar cert-manager (si no existe)
        run: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.yaml

      - name: Crear ClusterIssuer (Let's Encrypt)
        run: kubectl apply -f k8s/cluster-issuer.yaml

      - name: Asignar IP estatica al Ingress NGINX
        run: kubectl apply -f k8s/nginx-service-patch.yaml

      - name: Desplegar frontend (Deployment + Service)
        run: kubectl apply -f k8s/frontend.yaml

      - name: Crear Ingress para frontend con cert-manager
        run: kubectl apply -f k8s/frontend-ingress.yaml
