name: Build y Push Docker Images a Docker Hub

on:
  push: #rama
    branches: [ despliegue ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
        run: terraform apply -auto-approve

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # - name: Build and push backend image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./backend-djangoAPI
      #     push: true
      #     tags: enzobianchi8/backend:latest

      # - name: Build and push frontend image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./frontend
      #     push: true
      #     tags: enzobianchi8/frontend:latest

      - name: Autenticación Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

      - name: Instalar gcloud y kubectl
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
          install_components: 'kubectl'

      - name: Obtener credenciales de GKE
        run: |
          gcloud container clusters get-credentials gke-cluster --region=us-east4 --project=psychic-expanse-465922-f0

      - name: Deploy backend to Kubernetes
        run: kubectl apply -f k8s/backend.yaml

      - name: Deploy database to Kubernetes
        run: kubectl apply -f k8s/db.yaml

      - name: Deploy frontend to Kubernetes
        run: kubectl apply -f k8s/frontend.yaml

      - name: Deploy Managed Certificate
        run: kubectl apply -f k8s/frontend-managed-cert.yaml

      - name: Deploy Ingress with TLS
        run: kubectl apply -f k8s/frontend-ingress.yaml

      - name: Deploy Managed Certificate
        run: kubectl apply -f k8s/backend-managed-cert.yaml

      - name: Deploy Ingress with TLS
        run: kubectl apply -f k8s/backend-ingress.yaml
